version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-share-v1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1syw9wein8vbv"
s3_prefix = "test-share-v1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
